---
repo-name: peripherals-basecamp
categories:
- Project Management
- Collaboration
display-name: Basecamp
manufacture: Basecamp
product: 
description: Basecamp is a popular tool for project management and our integration
  gives you the data at your fingertips.
thumbnail: thumbnail.png
